### ISSUE TITLE
doesn't work with oc 8.2.1

### ISSUE THREAD

**Issue by tessus** [interfasys/sharelinks#6]
This plugin worked great until I upgraded oc from 8.1.4 to 8.2.1.

Now there's no button anymore to change the link to the Gallery link. I'm using Gallery+ 14.3.0 and Share Links 1.0.1.

**Comment by tessus** [comment]
@oparoz do you need any other info? there's nothing in the log file.

**Comment by oparoz** [comment]
@tessus Thanks for the report, I've just noticed that the app was not restricted to <8.2, which was a mistake (or an automatic change in the app store?). It cannot be used in its current state because there is no more share dropdown in the Files app, instead, the new side-bar has to be hacked. I haven't looked at it yet and don't know if it's easily doable.

**Comment by tessus** [comment]
@oparoz argh, too bad. this was really handy, since this is missing in core...
I hope you find a way to get it working again.

**Comment by oparoz** [comment]
I've had to find a way since I'm migrating to 8.2.3, so expect a new release soon.
